export enum RoutesName {
    loginRoute = "auth/login",
    registerRoute = "auth/register",
    dashboard = "dashboard",
    resetRoute = "auth/reset",
    notFound = "not-found",
    untMode = "dashboard/unt-mode",
    passUnt = "dashboard/pass-unt",
    passUntSingle = "dashboard/single-subject-unt",
    passUntExam = "dashboard/pass-unt-exam",
    resultUnt = "dashboard/unt-result",
    stepRoute = "step",
    subStepRoute = "sub-step",
    subStepExam = "sub-step-exam",
    untStats = "dashboard/unt-statistics",
    tournamentList = "dashboard/tournament-list",
    tournamentDetail = "dashboard/tournament-detail",
}
