export enum RoutesName {
    loginRoute = "auth/login",
    registerRoute = "auth/register",
    dashboard = "dashboard",
    resetRoute = "auth/reset",
    notFound = "not-found",
    untMode = "dashboard/unt-mode",
    passUnt = "dashboard/pass-unt",
    passUntSingle = "dashboard/single-subject-unt",
    passUntExam = "dashboard/pass-unt-exam",
    resultUnt = "dashboard/unt-result",
    stepRoute = "dashboard/step",
    subStepRoute = "dashboard/sub-step",
    subStepExam = "dashboard/sub-step-exam",
    subStepResultExam = "dashboard/result-exam",
    untStats = "dashboard/unt-statistics",
    tournamentList = "dashboard/tournament-list",
    tournamentDetail = "dashboard/tournament-detail",
    subTournamentDetail = "dashboard/sub-tournament-detail"
}
