export enum RoutesName {
    loginRoute = "auth/login",
    registerRoute = "auth/register",
    dashboard = "dashboard/index",
    teacher = "teacher/index",
    teacherClassrooms = "classrooms",
    studentClassrooms = "classrooms",
    resetRoute = "auth/reset",
    notFound = "not-found",
    untMode = "dashboard/unt-mode",
    passUnt = "dashboard/pass-unt",
    passUntSingle = "dashboard/single-subject-unt",
    passUntExam = "dashboard/pass-unt-exam",
    resultUnt = "dashboard/unt-result",
    stepRoute = "step",
    subStepRoute = "sub-step",
    subStepExam = "sub-step-exam",
    subStepResultExam = "result-exam",
    untStats = "dashboard/unt-statistics",
    tournamentList = "dashboard/tournament-list",
    tournamentDetail = "dashboard/tournament-detail",
    subTournamentDetail = "dashboard/sub-tournament-detail",
    resultByAttemptId = "dashboard/result-attempt",
    statByAttemptId = "dashboard/stat-attempt",
    statBySubjectId = "dashboard/stat-subject",
    myProfile = "my-profile",
}
